name: "JSUB"
title: "JSUB"
description: "Job Submission Utility Bundle"

encoding: utf-8
timezone: Asia/Shanghai

collections:
  docs:
    permalink: /docs/:path/
    output: true
  exts:
    permalink: /exts/:path/
    output: true

defaults:
  -
    scope:
      path: _docs
      type: docs
    values:
      layout: docs
  -
    scope:
      path: _exts
      type: exts
    values:
      layout: exts

sass:
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - TODO
  - LICENSE
  - README.md
